// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type Product struct {
	ID          sql.NullInt64 `json:"id"`
	Pid         string        `json:"pid"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	UnitName    string        `json:"unitName"`
	PriceSol    float64       `json:"priceSol"`
	PriceUsd    float64       `json:"priceUsd"`
	CreatedAt   time.Time     `json:"created_at"`
}
