// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	GetProduct(ctx context.Context, name string) (Product, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
}

var _ Querier = (*Queries)(nil)
